"""
Pydantic schemas for Session endpoints.

These schemas define the shape of data for API requests and responses
related to scan sessions.
"""

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, field_validator
from app.models.session import SessionStatus


# ============================================================================
# Request Schemas (what clients send to the API)
# ============================================================================

class SessionCreate(BaseModel):
    """
    Schema for creating a new scan session.

    Used by: POST /api/v1/sessions

    Fields that are NOT included (auto-generated):
    - id: Generated by database
    - user_id: Extracted from authenticated user (future)
    - status: Defaults to ACTIVE
    - created_at: Set by database
    - updated_at: Set by database
    """

    patient_identifier: Optional[str] = Field(
        None,
        max_length=100,
        description="Optional patient/study identifier (use anonymized ID, NOT PHI)",
        examples=["STUDY-2024-001", "PATIENT-12345"]
    )

    notes: Optional[str] = Field(
        None,
        max_length=2000,
        description="Optional notes or comments about this session",
        examples=["Initial cardiac screening", "Follow-up scan"]
    )

    @field_validator('patient_identifier')
    @classmethod
    def validate_patient_identifier(cls, v: Optional[str]) -> Optional[str]:
        """Ensure patient identifier doesn't contain obvious PHI."""
        if v:
            v = v.strip()
            # Basic check: warn if it looks like it might contain a name
            # (This is not foolproof, just a basic sanity check)
            if len(v) == 0:
                return None
        return v

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "patient_identifier": "STUDY-2024-001",
                    "notes": "Cardiac 4-chamber view assessment"
                },
                {
                    "patient_identifier": None,
                    "notes": "Training session"
                }
            ]
        }
    }


class SessionUpdate(BaseModel):
    """
    Schema for updating an existing session.

    Used by: PATCH /api/v1/sessions/{id}

    All fields are optional - only provided fields will be updated.
    """

    status: Optional[SessionStatus] = Field(
        None,
        description="Session status"
    )

    notes: Optional[str] = Field(
        None,
        max_length=2000,
        description="Session notes"
    )

    patient_identifier: Optional[str] = Field(
        None,
        max_length=100,
        description="Patient/study identifier"
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "status": "completed",
                    "notes": "Session completed successfully"
                }
            ]
        }
    }


# ============================================================================
# Response Schemas (what the API sends to clients)
# ============================================================================

class SessionResponse(BaseModel):
    """
    Schema for session data in API responses.

    This is what clients receive when they:
    - Create a session (POST)
    - Get a session (GET)
    - List sessions (GET)
    - Update a session (PATCH)

    Includes computed fields like image_count and comparison_count.
    """

    id: int = Field(
        description="Unique session identifier"
    )

    user_id: int = Field(
        description="ID of user who created this session"
    )

    patient_identifier: Optional[str] = Field(
        None,
        description="Patient/study identifier"
    )

    status: SessionStatus = Field(
        description="Current session status"
    )

    notes: Optional[str] = Field(
        None,
        description="Session notes"
    )

    created_at: datetime = Field(
        description="When the session was created"
    )

    updated_at: datetime = Field(
        description="When the session was last updated"
    )

    # These will be populated by the API route if needed
    image_count: Optional[int] = Field(
        None,
        description="Number of images in this session"
    )

    comparison_count: Optional[int] = Field(
        None,
        description="Number of comparisons in this session"
    )

    model_config = {
        "from_attributes": True,  # Allows converting from SQLAlchemy models
        "json_schema_extra": {
            "examples": [
                {
                    "id": 1,
                    "user_id": 1,
                    "patient_identifier": "STUDY-2024-001",
                    "status": "active",
                    "notes": "Cardiac assessment",
                    "created_at": "2024-11-15T12:00:00Z",
                    "updated_at": "2024-11-15T12:00:00Z",
                    "image_count": 5,
                    "comparison_count": 3
                }
            ]
        }
    }


class SessionDetail(SessionResponse):
    """
    Detailed session response with related data.

    Used when fetching a single session with all its images and comparisons.
    Extends SessionResponse with nested data.

    Used by: GET /api/v1/sessions/{id}?include=images,comparisons
    """

    # Will be populated with ImageResponse objects
    images: Optional[list] = Field(
        None,
        description="All images in this session"
    )

    # Will be populated with ComparisonResponse objects
    comparisons: Optional[list] = Field(
        None,
        description="All comparisons in this session"
    )

    model_config = {
        "from_attributes": True,
        "json_schema_extra": {
            "examples": [
                {
                    "id": 1,
                    "user_id": 1,
                    "patient_identifier": "STUDY-2024-001",
                    "status": "active",
                    "notes": "Cardiac assessment",
                    "created_at": "2024-11-15T12:00:00Z",
                    "updated_at": "2024-11-15T12:00:00Z",
                    "image_count": 2,
                    "comparison_count": 1,
                    "images": [],
                    "comparisons": []
                }
            ]
        }
    }


# ============================================================================
# Helper Schemas
# ============================================================================

class SessionListResponse(BaseModel):
    """
    Paginated list of sessions.

    Used by: GET /api/v1/sessions
    """

    items: list[SessionResponse] = Field(
        description="List of sessions"
    )

    total: int = Field(
        description="Total number of sessions (for pagination)"
    )

    page: int = Field(
        default=1,
        description="Current page number"
    )

    page_size: int = Field(
        default=20,
        description="Number of items per page"
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "items": [
                        {
                            "id": 1,
                            "user_id": 1,
                            "patient_identifier": "STUDY-001",
                            "status": "active",
                            "notes": None,
                            "created_at": "2024-11-15T12:00:00Z",
                            "updated_at": "2024-11-15T12:00:00Z",
                            "image_count": 3,
                            "comparison_count": 2
                        }
                    ],
                    "total": 15,
                    "page": 1,
                    "page_size": 20
                }
            ]
        }
    }
